apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-vcluster-external-argocd
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          appSecretName: loft-demo-org-cred
          labels:
            - create-pr-vcluster-external-argocd
          owner: loft-demos
          repo: training-app
        requeueAfterSeconds: 30
        template:
          metadata: {}
          spec:
            destination: {}
            project: ''
  template:
    metadata:
      name: training-app-pr-{{number}}-vcluster
    spec:
      destination:
        name: in-cluster
        namespace: p-auth-core
      info:
        - name: PR vCluster Argo CD URL
          value: https://argocd-training.us.demo.dev
        - name: GitHub PR
          value: https://github.com/loft-demos/training-app/pull/{{number}}
      project: loft-auth-core
      source:
        kustomize:
          namePrefix: training-app-pr-{{number}}-
          patches:
            - patch: |-
                - op: add
                  path: /metadata/labels/vclusterProjectId
                  value: auth-core
                - op: add
                  path: /metadata/labels/vclusterName
                  value: training-app-pr-{{number}}-vcluster
                - op: add
                  path: /metadata/labels/repo
                  value: training-app
                - op: add
                  path: /metadata/labels/prLabel
                  value: 'create-pr-vcluster-external-argocd'
                - op: add
                  path: /metadata/labels/prNumber
                  value: '{{number}}'
                - op: add
                  path: /metadata/labels/targetRevision
                  value: '{{head_sha}}'
                - op: add
                  path: /metadata/labels/headShortSha
                  value: '{{head_short_sha}}'
                - op: add
                  path: /metadata/labels/headBranch
                  value: '{{branch}}'
              target:
                kind: VirtualClusterInstance
                name: vcluster
        path: vcluster-use-cases/argocd-vcluster-pull-request-environments/kustomize
        repoURL: https://github.com/loft-demos/training-app.git
        targetRevision: '{{branch}}'
      syncPolicy:
        automated:
          selfHeal: true
